version: '3'

services:

    app:
        build: 
            context: .
            dockerfile: Dockerfile.prod
        container_name: micro-videos-app
        entrypoint: dockerize -wait tcp://db:3306 -timeout 40s
        volumes:
            - .:/var/www
        depends_on:
            - db
            - redis

    nginx:
        build: .docker/nginx
        container_name: micro-videos-nginx
        restart: always
        tty: true
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
        depends_on:
            - app

    db:
        build: ./.docker/mysql
        container_name: micro-videos-db
        restart: always
        tty: true
        ports:
            - "33006:3306"
        volumes:
            - ./.docker/mysql:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root


    redis:
        image: redis:alpine
        container_name: micro-videos-redis
        expose:
            - 6379

networks:
  default:
    external:
      name: cloudbuild
